#1. DATASET OVERVIEW

In [ ]:
# 1. Dataset Overview
import pandas as pd
import numpy as np
from pathlib import Path

# Dataset directory
DATASET_PATH = Path("../content")

# Load datasets
datasets = {
    "customers": pd.read_csv(DATASET_PATH / "olist_customers_dataset.csv"),
    "geolocation": pd.read_csv(DATASET_PATH / "olist_geolocation_dataset.csv"),
    "order_items": pd.read_csv(DATASET_PATH / "olist_order_items_dataset.csv"),
    "order_payments": pd.read_csv(DATASET_PATH / "olist_order_payments_dataset.csv"),
    "order_reviews": pd.read_csv(DATASET_PATH / "olist_order_reviews_dataset.csv"),
    "orders": pd.read_csv(DATASET_PATH / "olist_orders_dataset.csv"),
    "products": pd.read_csv(DATASET_PATH / "olist_products_dataset.csv"),
    "sellers": pd.read_csv(DATASET_PATH / "olist_sellers_dataset.csv"),
    "category_translation": pd.read_csv(DATASET_PATH / "product_category_name_translation.csv")
}

In [ ]:
for table_name, df in datasets.items():

    print("="*80)
    print(table_name.upper())
    print("="*80)

    display(
        pd.DataFrame({
            "Column": df.columns,
            "Data Type": df.dtypes.astype(str)
        })
    )

================================================================================
CUSTOMERS
================================================================================

                                            Column Data Type
customer_id                            customer_id    object
customer_unique_id              customer_unique_id    object
customer_zip_code_prefix  customer_zip_code_prefix     int64
customer_city                        customer_city    object
customer_state                      customer_state    object

================================================================================
GEOLOCATION
================================================================================

                                                  Column Data Type
geolocation_zip_code_prefix  geolocation_zip_code_prefix     int64
geolocation_lat                          geolocation_lat   float64
geolocation_lng                          geolocation_lng   float64
geolocation_city                        geolocation_city    object
geolocation_state                      geolocation_state    object

================================================================================
ORDER_ITEMS
================================================================================

                                  Column Data Type
order_id                        order_id    object
order_item_id              order_item_id     int64
product_id                    product_id    object
seller_id                      seller_id    object
shipping_limit_date  shipping_limit_date    object
price                              price   float64
freight_value              freight_value   float64

================================================================================
ORDER_PAYMENTS
================================================================================

                                    Column Data Type
order_id                          order_id    object
payment_sequential      payment_sequential     int64
payment_type                  payment_type    object
payment_installments  payment_installments     int64
payment_value                payment_value   float64

================================================================================
ORDER_REVIEWS
================================================================================

                                          Column Data Type
review_id                              review_id    object
order_id                                order_id    object
review_score                        review_score     int64
review_comment_title        review_comment_title    object
review_comment_message    review_comment_message    object
review_creation_date        review_creation_date    object
review_answer_timestamp  review_answer_timestamp    object

================================================================================
ORDERS
================================================================================

                                                      Column Data Type
order_id                                            order_id    object
customer_id                                      customer_id    object
order_status                                    order_status    object
order_purchase_timestamp            order_purchase_timestamp    object
order_approved_at                          order_approved_at    object
order_delivered_carrier_date    order_delivered_carrier_date    object
order_delivered_customer_date  order_delivered_customer_date    object
order_estimated_delivery_date  order_estimated_delivery_date    object

================================================================================
PRODUCTS
================================================================================

                                                Column Data Type
product_id                                  product_id    object
product_category_name            product_category_name    object
product_name_lenght                product_name_lenght   float64
product_description_lenght  product_description_lenght   float64
product_photos_qty                  product_photos_qty   float64
product_weight_g                      product_weight_g   float64
product_length_cm                    product_length_cm   float64
product_height_cm                    product_height_cm   float64
product_width_cm                      product_width_cm   float64

================================================================================
SELLERS
================================================================================

                                        Column Data Type
seller_id                            seller_id    object
seller_zip_code_prefix  seller_zip_code_prefix     int64
seller_city                        seller_city    object
seller_state                      seller_state    object

================================================================================
CATEGORY_TRANSLATION
================================================================================

                                                      Column Data Type
product_category_name                  product_category_name    object
product_category_name_english  product_category_name_english    object

In [ ]:
for table_name, df in datasets.items():

    print("="*80)
    print(table_name.upper())
    print("="*80)

    display(df.head())

================================================================================
CUSTOMERS
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

================================================================================
GEOLOCATION
================================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

================================================================================
ORDER_ITEMS
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

================================================================================
ORDER_PAYMENTS
================================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

================================================================================
ORDER_REVIEWS
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

================================================================================
ORDERS
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

================================================================================
PRODUCTS
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

================================================================================
SELLERS
================================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

================================================================================
CATEGORY_TRANSLATION
================================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
summary = []

for table_name, df in datasets.items():

    summary.append({
        "Table": table_name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Memory (MB)": round(df.memory_usage(deep=True).sum()/1024**2,2)
    })

dataset_summary = pd.DataFrame(summary)

dataset_summary

                  Table     Rows  Columns  Memory (MB)
0             customers    99441        5        26.59
1           geolocation  1000163        5       129.38
2           order_items   112650        7        35.99
3        order_payments   103886        5        16.23
4         order_reviews    99224        7        39.12
5                orders    99441        8        52.94
6              products    32951        9         6.30
7               sellers     3095        4         0.59
8  category_translation       71        2         0.01

In [ ]:
for table_name, df in datasets.items():

    object_columns = df.select_dtypes(include="object").columns

    if len(object_columns) == 0:
        continue

    print("=" * 100)
    print(f"{table_name.upper()} - CATEGORICAL VALUE DISTRIBUTION")
    print("=" * 100)

    for column in object_columns:

        print(f"\nColumn: {column}")

        display(
            df[column]
            .value_counts(dropna=False)
            .rename_axis("Value")
            .reset_index(name="Count")
        )

====================================================================================================
CUSTOMERS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: customer_id

                                  Value  Count
0      274fa6071e5e17fe303b9748641082c8      1
1      e5ed7280cd1a3ac2ba29fd6650d8867c      1
2      c6ece8a5137f3c9c3a3a12302a19a2ac      1
3      821a7275a08f32975caceff2e08ea262      1
4      5eef6cce1f34954c9e7004332388ccc7      1
...                                 ...    ...
99436  879864dab9bc3047522c92c82e1212b8      1
99437  4f2d8ab171c80ec8364f7c12e35b23ad      1
99438  b2b6027bc5c5109e529d4dc6358b12c3      1
99439  4e7b3e00288586ebd08712fdd0374a03      1
99440  18955e83d337fd6b2def6b18a428ac77      1

[99441 rows x 2 columns]

Column: customer_unique_id

                                  Value  Count
0      8d50f5eadf50201ccdcedfb9e2ac8455     17
1      3e43e6105506432c953e165fb2acf44c      9
2      ca77025e7201e3b30c44b472ff346268      7
3      1b6c7548a2a1f9037c1fd3ddfed95f33      7
4      6469f99c1f9dfae7733b25662e7f1782      7
...                                 ...    ...
96091  4f83c83b7ff5b544a8c75dcb8ad66e2e      1
96092  3fe413dde400746c53c5d0d38b266ca2      1
96093  289e1d1ce11a14bb169775d58ad2f1c2      1
96094  ec83d060d9a0abba4b409c544c744c2f      1
96095  211e4234ffca5cec9b0ab183a1009256      1

[96096 rows x 2 columns]

Column: customer_city

                         Value  Count
0                    sao paulo  15540
1               rio de janeiro   6882
2               belo horizonte   2773
3                     brasilia   2131
4                     curitiba   1521
...                        ...    ...
4114              olhos d'agua      1
4115                  pacotuba      1
4116  sao sebastiao do paraiba      1
4117            benedito leite      1
4118             campos verdes      1

[4119 rows x 2 columns]

Column: customer_state

   Value  Count
0     SP  41746
1     RJ  12852
2     MG  11635
3     RS   5466
4     PR   5045
5     SC   3637
6     BA   3380
7     DF   2140
8     ES   2033
9     GO   2020
10    PE   1652
11    CE   1336
12    PA    975
13    MT    907
14    MA    747
15    MS    715
16    PB    536
17    PI    495
18    RN    485
19    AL    413
20    SE    350
21    TO    280
22    RO    253
23    AM    148
24    AC     81
25    AP     68
26    RR     46

====================================================================================================
GEOLOCATION - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: geolocation_city

               Value   Count
0          sao paulo  135800
1     rio de janeiro   62151
2     belo horizonte   27805
3          são paulo   24918
4           curitiba   16593
...              ...     ...
8006     tres irmaos       1
8007     morro chato       1
8008  valao do barro       1
8009      jordanésia       1
8010    são valentim       1

[8011 rows x 2 columns]

Column: geolocation_state

   Value   Count
0     SP  404268
1     MG  126336
2     RJ  121169
3     RS   61851
4     PR   57859
5     SC   38328
6     BA   36045
7     GO   20139
8     ES   16748
9     PE   16432
10    DF   12986
11    MT   12031
12    CE   11674
13    PA   10853
14    MS   10431
15    MA    7853
16    PB    5538
17    RN    5041
18    PI    4549
19    AL    4183
20    TO    3576
21    SE    3563
22    RO    3478
23    AM    2432
24    AC    1301
25    AP     853
26    RR     646

====================================================================================================
ORDER_ITEMS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: order_id

                                  Value  Count
0      8272b63d03f5f79c56e9e4120aec44ef     21
1      1b15974a0141d54e36626dca3fdc731a     20
2      ab14fdcfbe524636d65ee38360e22ce8     20
3      9ef13efd6949e4573a18964dd1bbe7f5     15
4      428a2f660dc84138d969ccd69a0ab6d5     15
...                                 ...    ...
98661  5a082b558a3798d3e36d93bfa8ca1eae      1
98662  5a07264682e0b8fbb3f166edbbffc6e8      1
98663  5a071192a28951b76774e5a760c8c9b7      1
98664  5a06fc966a12b41bf401b344464fd4b1      1
98665  5a0e5ad33542c79b10be87a344ee0086      1

[98666 rows x 2 columns]

Column: product_id

                                  Value  Count
0      aca2eb7d00ea1a7b8ebd4e68314663af    527
1      99a4788cb24856965c36a24e339b6058    488
2      422879e10f46682990de24d770e7f83d    484
3      389d119b48cf3043d311335e499d9c6b    392
4      368c6c730842d78016ad823897a372db    388
...                                 ...    ...
32946  038c0dd7c1e48a1588f8919a0c305727      1
32947  aa20709d44e96059764f1b0386d3bcfa      1
32948  9ae3dacfd2327107a1e28274fac25a4e      1
32949  0c398b245c9b74ef2bf4343b6fe73237      1
32950  446295cf6f689d4db477145815362608      1

[32951 rows x 2 columns]

Column: seller_id

                                 Value  Count
0     6560211a19b47992c3666cc44a7e94c0   2033
1     4a3ca9315b744ce9f8e9374361493884   1987
2     1f50f920176fa81dab994f9023523100   1931
3     cc419e0650a3c5ba77189a1882b7556a   1775
4     da8622b14eb17ae2831f4ac5b9dab84a   1551
...                                ...    ...
3090  6c77cd583b36a13aacccf2b3ee23e233      1
3091  79b93a308a97792cf53ac75f46da00b5      1
3092  04ee0ec01589969663ba5967c0e0bdc0      1
3093  7d81e74a4755b552267cd5e081563028      1
3094  20f0aeea30bc3b8c4420be8ced4226c0      1

[3095 rows x 2 columns]

Column: shipping_limit_date

                     Value  Count
0      2017-07-21 18:25:23     21
1      2018-03-01 02:50:48     21
2      2017-08-30 14:30:23     20
3      2017-12-21 02:30:41     15
4      2017-11-30 10:30:51     15
...                    ...    ...
93313  2018-03-29 20:07:49      1
93314  2018-02-28 12:08:37      1
93315  2017-08-21 03:33:13      1
93316  2018-05-16 20:57:03      1
93317  2018-04-09 05:08:33      1

[93318 rows x 2 columns]

====================================================================================================
ORDER_PAYMENTS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: order_id

                                  Value  Count
0      fa65dad1b0e818e3ccc5cb0e39231352     29
1      ccf804e764ed5650cd8759557269dc13     26
2      285c2e15bebd4ac83635ccc563dc71f4     22
3      895ab968e7bb0d5659d16cd74cd1650c     21
4      fedcd9f7ccdc8cba3a18defedd1a5547     19
...                                 ...    ...
99435  646e62df54f3e236eb6d5ff3b31429b8      1
99436  e115da7a49ec2acf622e1f31da65cfb9      1
99437  f22592e01ddc0711e6794f900fa5e787      1
99438  89a52f9735ee199f8c4583cd8d77de4c      1
99439  5a8cbc60b032f344459aae65f0c01d26      1

[99440 rows x 2 columns]

Column: payment_type

         Value  Count
0  credit_card  76795
1       boleto  19784
2      voucher   5775
3   debit_card   1529
4  not_defined      3

====================================================================================================
ORDER_REVIEWS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: review_id

                                  Value  Count
0      4548534449b1f572e357211b90724f1b      3
1      44e9f871226d8a130de3fc39dfbdf0c5      3
2      2d6ac45f859465b5c185274a1c929637      3
3      ddc52555ca27b0fe67d5255147682d2d      3
4      08528f70f579f0c830189efc523d2182      3
...                                 ...    ...
98405  ca475b77fcc618551ef9d516c3f61b88      1
98406  95a8d0270bdd512d3c2e03a885f21d27      1
98407  93016126c7a3060a49c6975fab7a9c16      1
98408  0a77ca646b0b9b7a209e97589adf9d88      1
98409  11d8992bd767ff693cfa2fb3f930f65a      1

[98410 rows x 2 columns]

Column: order_id

                                  Value  Count
0      03c939fd7fd3b38f8485a0f95798f1f6      3
1      8e17072ec97ce29f0e1f111e598b0c85      3
2      c88b1d1b157a9999ce368f218a407141      3
3      df56136b8031ecd28e200bb18e6ddb2e      3
4      843be4a0dcdb9716de7652d53af4acab      2
...                                 ...    ...
98668  bad0467c52f23cdc71e9fa139d4a8afd      1
98669  6acf2b0f288195a72858fa65ff2c43c7      1
98670  4634ad13b4414c83524f5efb0ef21a0b      1
98671  891ba4502e28c6f12a1413e7b915c15d      1
98672  08ea65e91550ee222548404d16eb06b4      1

[98673 rows x 2 columns]

Column: review_comment_title

                          Value  Count
0                           NaN  87656
1                     Recomendo    423
2                     recomendo    345
3                           Bom    293
4               super recomendo    270
...                         ...    ...
4523  produto com lacre violado      1
4524            Atraso Entrega       1
4525                   Top Show      1
4526             Foi cancelado       1
4527    Entregue como prometido      1

[4528 rows x 2 columns]

Column: review_comment_message

                                                   Value  Count
0                                                    NaN  58247
1                                              Muito bom    230
2                                                    Bom    189
3                                              muito bom    122
4                                                    bom    107
...                                                  ...    ...
36155                 chegou bem antes do prazo previsto      1
36156                     Ja respondi esse questionario.      1
36157       Produto não informado como paralelo/réplica       1
36158  Foi entregue rapidamente e o produto veio perf...      1
36159                    recebi no tempo certo.obrigado.      1

[36160 rows x 2 columns]

Column: review_creation_date

                   Value  Count
0    2017-12-19 00:00:00    463
1    2018-08-28 00:00:00    452
2    2017-12-20 00:00:00    440
3    2018-05-19 00:00:00    434
4    2018-05-15 00:00:00    425
..                   ...    ...
631  2016-10-09 00:00:00      1
632  2017-11-13 00:00:00      1
633  2018-07-30 00:00:00      1
634  2018-08-13 00:00:00      1
635  2016-11-06 00:00:00      1

[636 rows x 2 columns]

Column: review_answer_timestamp

                     Value  Count
0      2017-06-15 23:21:05      4
1      2017-08-30 11:18:29      3
2      2017-11-02 00:11:06      3
3      2018-03-30 00:29:09      3
4      2018-04-07 21:13:05      3
...                    ...    ...
98243  2018-05-13 13:19:11      1
98244  2018-03-19 12:59:37      1
98245  2017-10-17 13:50:53      1
98246  2018-03-10 00:10:21      1
98247  2017-12-05 06:49:39      1

[98248 rows x 2 columns]

====================================================================================================
ORDERS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: order_id

                                  Value  Count
0      66dea50a8b16d9b4dee7af250b4be1a5      1
1      6ec4642f9993cc34f826cfb9068e5a2f      1
2      38e9133ce29f6bbe35aed9c3863dce01      1
3      dfc6eb45a2753ed9e6c6ef4987b44503      1
4      6f46d42016226f77893ed3978d6903d0      1
...                                 ...    ...
99436  a4591c265e18cb1dcee52889e2d8acc3      1
99437  ad21c59c0840e6cb83a9ceb5573f8159      1
99438  949d5b44dbf5de918fe9c16f97b45f8a      1
99439  47770eb9100c2d0c44946d9cf07ec65d      1
99440  53cdb2fc8bc7dce0b6741e2150273451      1

[99441 rows x 2 columns]

Column: customer_id

                                  Value  Count
0      edb027a75a1449115f6b43211ae02a24      1
1      f00bb12620b7b232233cace1b229db18      1
2      ad312389a098ceff46ce92c4595c06d0      1
3      a046c690e0564ffde0ce611b5eee2c30      1
4      3803547f820b1e10b7ad9c7985f06753      1
...                                 ...    ...
99436  503740e9ca751ccdda7ba28e9ab8f608      1
99437  8ab97904e6daea8866dbdbc4fb7aad2c      1
99438  f88197465ea7920adcdbec7375364d82      1
99439  41ce2a54c0b03bf3443c3d931a367089      1
99440  b0830fb4747a6c6d20dea0b8c802d7ef      1

[99441 rows x 2 columns]

Column: order_status

         Value  Count
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7     approved      2

Column: order_purchase_timestamp

                     Value  Count
0      2018-08-02 12:06:07      3
1      2018-04-11 10:48:14      3
2      2018-08-02 12:05:26      3
3      2018-02-19 15:37:47      3
4      2017-11-20 11:46:30      3
...                    ...    ...
98870  2018-03-17 23:46:08      1
98871  2017-07-12 13:42:13      1
98872  2018-03-31 14:24:53      1
98873  2018-01-09 12:21:52      1
98874  2018-01-02 14:04:54      1

[98875 rows x 2 columns]

Column: order_approved_at

                     Value  Count
0                      NaN    160
1      2018-02-27 04:31:10      9
2      2017-11-07 07:30:29      7
3      2018-02-06 05:31:52      7
4      2018-02-27 04:31:01      7
...                    ...    ...
90729  2018-04-16 15:15:25      1
90730  2017-03-13 02:22:34      1
90731  2018-01-25 15:09:37      1
90732  2017-06-02 20:05:13      1
90733  2018-08-16 11:50:15      1

[90734 rows x 2 columns]

Column: order_delivered_carrier_date

                     Value  Count
0                      NaN   1783
1      2018-05-09 15:48:00     47
2      2018-05-10 18:29:00     32
3      2018-05-07 12:31:00     21
4      2018-07-24 16:07:00     16
...                    ...    ...
81014  2018-01-31 23:06:09      1
81015  2018-03-09 19:38:48      1
81016  2018-03-28 22:34:32      1
81017  2017-06-13 09:34:17      1
81018  2017-11-22 19:58:55      1

[81019 rows x 2 columns]

Column: order_delivered_customer_date

                     Value  Count
0                      NaN   2965
1      2017-06-19 18:47:51      3
2      2016-10-27 17:32:07      3
3      2018-05-14 20:02:44      3
4      2018-05-08 19:36:48      3
...                    ...    ...
95660  2018-06-29 11:21:34      1
95661  2018-01-09 21:42:59      1
95662  2018-06-19 17:02:46      1
95663  2018-08-27 21:08:47      1
95664  2017-06-12 13:32:57      1

[95665 rows x 2 columns]

Column: order_estimated_delivery_date

                   Value  Count
0    2017-12-20 00:00:00    522
1    2018-03-12 00:00:00    516
2    2018-05-29 00:00:00    513
3    2018-03-13 00:00:00    513
4    2018-02-14 00:00:00    507
..                   ...    ...
454  2017-01-19 00:00:00      1
455  2016-10-20 00:00:00      1
456  2016-10-28 00:00:00      1
457  2016-09-30 00:00:00      1
458  2016-10-27 00:00:00      1

[459 rows x 2 columns]

====================================================================================================
PRODUCTS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: product_id

                                  Value  Count
0      106392145fca363410d287a815be6de4      1
1      1e9e8ef04dbcff4541ed26657ea517e5      1
2      3aa071139cb16b67ca9e5dea641aaa2f      1
3      96bd76ec8810374ed1b65e291975717f      1
4      cef67bcfe19066a932b7673e239eb23d      1
...                                 ...    ...
32946  03b63c5fc16691530586ae020c345514      1
32947  14aa47b7fe5c25522b47b4b29c98dcb9      1
32948  8c92109888e8cdf9d66dc7e463025574      1
32949  37cc742be07708b53a98702e77a21a02      1
32950  2548af3e6e77a690cf3eb6368e9ab61e      1

[32951 rows x 2 columns]

Column: product_category_name

                            Value  Count
0                 cama_mesa_banho   3029
1                   esporte_lazer   2867
2                moveis_decoracao   2657
3                    beleza_saude   2444
4           utilidades_domesticas   2335
..                            ...    ...
69  fashion_roupa_infanto_juvenil      5
70                casa_conforto_2      5
71                       pc_gamer      3
72             seguros_e_servicos      2
73              cds_dvds_musicais      1

[74 rows x 2 columns]

====================================================================================================
SELLERS - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: seller_id

                                 Value  Count
0     9e25199f6ef7e7c347120ff175652c3b      1
1     3442f8959a84dea7ee197c632cb2df15      1
2     d1b65fc7debc3361ea86b5f14c68d2e2      1
3     ce3ad9de960102d0677a81f5d0bb7b2d      1
4     c0f3eea2e14555b6faeea3dd58c1b1c3      1
...                                ...    ...
3090  a7a9b880c49781da66651ccf4ba9ac38      1
3091  8cb7c5ddf41f4d506eba76e9a4702a25      1
3092  ccc4bbb5f32a6ab2b7066a4130f114e3      1
3093  768a86e36ad6aae3d03ee3c6433d61df      1
3094  1b938a7ec6ac5061a66a3766e0e75f90      1

[3095 rows x 2 columns]

Column: seller_city

                                      Value  Count
0                                 sao paulo    694
1                                  curitiba    127
2                            rio de janeiro     96
3                            belo horizonte     68
4                            ribeirao preto     52
..                                      ...    ...
606                                    ipua      1
607                                   muqui      1
608                                 timoteo      1
609                            pouso alegre      1
610  rio de janeiro, rio de janeiro, brasil      1

[611 rows x 2 columns]

Column: seller_state

   Value  Count
0     SP   1849
1     PR    349
2     MG    244
3     SC    190
4     RJ    171
5     RS    129
6     GO     40
7     DF     30
8     ES     23
9     BA     19
10    CE     13
11    PE      9
12    PB      6
13    MS      5
14    RN      5
15    MT      4
16    RO      2
17    SE      2
18    AC      1
19    PI      1
20    MA      1
21    AM      1
22    PA      1

====================================================================================================
CATEGORY_TRANSLATION - CATEGORICAL VALUE DISTRIBUTION
====================================================================================================

Column: product_category_name

                            Value  Count
0                    beleza_saude      1
1          informatica_acessorios      1
2                      automotivo      1
3                 cama_mesa_banho      1
4                moveis_decoracao      1
..                            ...    ...
66                         flores      1
67             artes_e_artesanato      1
68                fraldas_higiene      1
69  fashion_roupa_infanto_juvenil      1
70             seguros_e_servicos      1

[71 rows x 2 columns]

Column: product_category_name_english

                        Value  Count
0               health_beauty      1
1       computers_accessories      1
2                        auto      1
3              bed_bath_table      1
4             furniture_decor      1
..                        ...    ...
66                    flowers      1
67      arts_and_craftmanship      1
68        diapers_and_hygiene      1
69  fashion_childrens_clothes      1
70      security_and_services      1

[71 rows x 2 columns]

**Findings**

- The dataset contains all major business entities of an e-commerce platform, including Customer, Order, Product, Seller, Payment, and Review.
- Nearly 100,000 customers made purchases between 2016 and 2018 across more than 8,000 cities in Brazil.
- The `product_category_name_translation` table provides English translations for product category names, enabling easier business analysis and reporting.
- The `geolocation` table is the largest dataset, containing over one million geographic location records.
- The dataset includes both transactional data and reference data, providing a solid foundation for building Dimension Tables in a Data Warehouse.

#2. Data Quality

In [ ]:
# 2. Data Quality Assessment
missing_summary = []

for table_name, df in datasets.items():

    total_rows = len(df)

    for column in df.columns:

        missing = df[column].isna().sum()

        missing_summary.append({

            "Table": table_name,

            "Column": column,

            "Missing Count": missing,

            "Missing Rate (%)": round(missing/total_rows*100,2)

        })

missing_summary = pd.DataFrame(missing_summary)

missing_summary.sort_values(
    "Missing Rate (%)",
    ascending=False
)

,Table,Column,Missing Count,Missing Rate (%)
25,order_reviews,review_comment_title,87656,88.34
26,order_reviews,review_comment_message,58247,58.70
35,orders,order_delivered_customer_date,2965,2.98
39,products,product_name_lenght,610,1.85
41,products,product_photos_qty,610,1.85
38,products,product_category_name,610,1.85
40,products,product_description_lenght,610,1.85
34,orders,order_delivered_carrier_date,1783,1.79
33,orders,order_approved_at,160,0.16
42,products,product_weight_g,2,0.01
45,products,product_width_cm,2,0.01
43,products,product_length_cm,2,0.01
44,products,product_height_cm,2,0.01
4,customers,customer_state,0,0.00
6,geolocation,geolocation_lat,0,0.00
5,geolocation,geolocation_zip_code_prefix,0,0.00
0,customers,customer_id,0,0.00
1,customers,customer_unique_id,0,0.00
2,customers,customer_zip_code_prefix,0,0.00
3,customers,customer_city,0,0.00
19,order_payments,payment_type,0,0.00
18,order_payments,payment_sequential,0,0.00
17,order_payments,order_id,0,0.00
16,order_items,freight_value,0,0.00
15,order_items,price,0,0.00
14,order_items,shipping_limit_date,0,0.00
13,order_items,seller_id,0,0.00
12,order_items,product_id,0,0.00
11,order_items,order_item_id,0,0.00
10,order_items,order_id,0,0.00
9,geolocation,geolocation_state,0,0.00
8,geolocation,geolocation_city,0,0.00
7,geolocation,geolocation_lng,0,0.00
23,order_reviews,order_id,0,0.00
20,order_payments,payment_installments,0,0.00
21,order_payments,payment_value,0,0.00
32,orders,order_purchase_timestamp,0,0.00
29,orders,order_id,0,0.00
30,orders,customer_id,0,0.00
31,orders,order_status,0,0.00
28,order_reviews,review_answer_timestamp,0,0.00
22,order_reviews,review_id,0,0.00
24,order_reviews,review_score,0,0.00
27,order_reviews,review_creation_date,0,0.00
37,products,product_id,0,0.00
36,orders,order_estimated_delivery_date,0,0.00
46,sellers,seller_id,0,0.00
47,sellers,seller_zip_code_prefix,0,0.00
48,sellers,seller_city,0,0.00
49,sellers,seller_state,0,0.00
50,category_translation,product_category_name,0,0.00
51,category_translation,product_category_name_english,0,0.00

In [ ]:
duplicate_summary = []

for table_name, df in datasets.items():

    duplicate_summary.append({

        "Table": table_name,

        "Total Rows": len(df),

        "Duplicate Rows": df.duplicated().sum(),

        "Duplicate Rate (%)":
        round(df.duplicated().mean()*100,2)

    })

duplicate_summary = pd.DataFrame(duplicate_summary)

duplicate_summary

                  Table  Total Rows  Duplicate Rows  Duplicate Rate (%)
0             customers       99441               0                0.00
1           geolocation     1000163          261831               26.18
2           order_items      112650               0                0.00
3        order_payments      103886               0                0.00
4         order_reviews       99224               0                0.00
5                orders       99441               0                0.00
6              products       32951               0                0.00
7               sellers        3095               0                0.00
8  category_translation          71               0                0.00

In [ ]:
quality_summary = []

for table_name, df in datasets.items():

    quality_summary.append({

        "Table": table_name,

        "Rows": len(df),

        "Columns": len(df.columns),

        "Missing Values": df.isna().sum().sum(),

        "Duplicate Rows": df.duplicated().sum()

    })

quality_summary = pd.DataFrame(quality_summary)

quality_summary

                  Table     Rows  Columns  Missing Values  Duplicate Rows
0             customers    99441        5               0               0
1           geolocation  1000163        5               0          261831
2           order_items   112650        7               0               0
3        order_payments   103886        5               0               0
4         order_reviews    99224        7          145903               0
5                orders    99441        8            4908               0
6              products    32951        9            2448               0
7               sellers     3095        4               0               0
8  category_translation       71        2               0               0

**Findings**

- Missing values are primarily concentrated in the `order_reviews` table.
- Duplicate records are found only in the `geolocation` table.
- No duplicate records were detected in the main transactional tables, including `orders`, `order_items`, and `order_payments`.
- Primary identifiers (`customer_id`, `order_id`, `product_id`, and `seller_id`) contain no missing values, ensuring reliable relationships between the core business entities.

In [ ]:
# 3. Relational Data Assessment
relationships = [
    ("customers", "customer_id", "orders", "customer_id"),
    ("orders", "order_id", "order_items", "order_id"),
    ("orders", "order_id", "order_payments", "order_id"),
    ("orders", "order_id", "order_reviews", "order_id"),
    ("products", "product_id", "order_items", "product_id"),
    ("sellers", "seller_id", "order_items", "seller_id"),
    (
        "category_translation",
        "product_category_name",
        "products",
        "product_category_name",
    ),
]

relationship_df = pd.DataFrame(
    relationships,
    columns=[
        "Parent Table",
        "Primary Key",
        "Child Table",
        "Foreign Key",
    ],
)

relationship_df

,Parent Table,Primary Key,Child Table,Foreign Key
0,customers,customer_id,orders,customer_id
1,orders,order_id,order_items,order_id
2,orders,order_id,order_payments,order_id
3,orders,order_id,order_reviews,order_id
4,products,product_id,order_items,product_id
5,sellers,seller_id,order_items,seller_id
6,category_translation,product_category_name,products,product_category_name

In [ ]:
primary_keys = {
    "customers": "customer_id",
    "orders": "order_id",
    "products": "product_id",
    "sellers": "seller_id",
    "order_reviews": "review_id",
    "category_translation": "product_category_name",
}

pk_summary = []

for table, pk in primary_keys.items():

    df = datasets[table]

    pk_summary.append({

        "Table": table,

        "Primary Key": pk,

        "Null": df[pk].isna().sum(),

        "Duplicate": df[pk].duplicated().sum()

    })

pd.DataFrame(pk_summary)

                  Table            Primary Key  Null  Duplicate
0             customers            customer_id     0          0
1                orders               order_id     0          0
2              products             product_id     0          0
3               sellers              seller_id     0          0
4         order_reviews              review_id     0        814
5  category_translation  product_category_name     0          0

In [ ]:
cardinality_summary = []

for parent_table, pk, child_table, fk in relationships:

    child = datasets[child_table]

    cardinality_summary.append({

        "Relationship":
        f"{parent_table} → {child_table}",

        "Unique Parent":
        child[fk].nunique(),

        "Total Child Rows":
        len(child)

    })

pd.DataFrame(cardinality_summary)

                      Relationship  Unique Parent  Total Child Rows
0               customers → orders          99441             99441
1             orders → order_items          98666            112650
2          orders → order_payments          99440            103886
3           orders → order_reviews          98673             99224
4           products → order_items          32951            112650
5            sellers → order_items           3095            112650
6  category_translation → products             73             32951

**Findings**

- Most tables exhibit one-to-many (1:N) relationships, while the `customers` and `orders` tables have a one-to-one (1:1) relationship based on `customer_id`.
- No orphan records were detected among the core business tables, indicating that the dataset maintains good referential integrity.

In [ ]:
# 4. Business Data Understanding
business_entities = pd.DataFrame({

    "Entity":[

        "Customer",
        "Order",
        "Order Item",
        "Product",
        "Seller",
        "Payment",
        "Review",
        "Geolocation"

    ],

    "Source Table":[

        "customers",
        "orders",
        "order_items",
        "products",
        "sellers",
        "order_payments",
        "order_reviews",
        "geolocation"

    ],

    "Description":[

        "Customer information",
        "Order information",
        "Purchased products",
        "Product information",
        "Seller information",
        "Payment transactions",
        "Customer reviews",
        "Geographical information"

    ]

})

business_entities

        Entity    Source Table               Description
0     Customer       customers      Customer information
1        Order          orders         Order information
2   Order Item     order_items        Purchased products
3      Product        products       Product information
4       Seller         sellers        Seller information
5      Payment  order_payments      Payment transactions
6       Review   order_reviews          Customer reviews
7  Geolocation     geolocation  Geographical information

In [ ]:
measure_summary = []

for table_name, df in datasets.items():

    numeric_columns = df.select_dtypes(include=["number"]).columns

    for column in numeric_columns:

        measure_summary.append({

            "Table": table_name,

            "Measure": column,

            "Data Type": str(df[column].dtype)

        })

measure_summary = pd.DataFrame(measure_summary)

measure_summary

             Table                      Measure Data Type
0        customers     customer_zip_code_prefix     int64
1      geolocation  geolocation_zip_code_prefix     int64
2      geolocation              geolocation_lat   float64
3      geolocation              geolocation_lng   float64
4      order_items                order_item_id     int64
5      order_items                        price   float64
6      order_items                freight_value   float64
7   order_payments           payment_sequential     int64
8   order_payments         payment_installments     int64
9   order_payments                payment_value   float64
10   order_reviews                 review_score     int64
11        products          product_name_lenght   float64
12        products   product_description_lenght   float64
13        products           product_photos_qty   float64
14        products             product_weight_g   float64
15        products            product_length_cm   float64
16        products            product_height_cm   float64
17        products             product_width_cm   float64
18         sellers       seller_zip_code_prefix     int64

**Findings**

- The dataset contains candidate business measures from the `order_items`, `order_payments`, and `products` tables.
- Transactional measures, such as `price`, `freight_value`, and `payment_value`, can serve as the foundation for calculating key business metrics, including revenue and shipping cost.
- Product-related numeric attributes provide additional information for analyzing product characteristics and supporting business insights.

| Source Table | Measure | Data Type | Meaning |
|--------------|---------|-----------|---------|
| order_items | `order_item_id` | int64 | Sequential identifier of an item within an order, which can be used to derive the total number of purchased items. |
| order_items | `price` | float64 | Monetary value of the purchased product, representing the product sales amount before shipping costs. |
| order_items | `freight_value` | float64 | Shipping cost charged for delivering the purchased product. |
| order_payments | `payment_value` | float64 | Total payment amount received for an order. |
| products | `product_name_lenght` | float64 | Number of characters in the product name, indicating the amount of product title information. |
| products | `product_description_lenght` | float64 | Number of characters in the product description, representing the level of product information detail. |
| products | `product_weight_g` | float64 | Weight of the product in grams. |
| products | `product_length_cm` | float64 | Length of the product in centimeters. |
| products | `product_height_cm` | float64 | Height of the product in centimeters. |
| products | `product_width_cm` | float64 | Width of the product in centimeters. |